### ISSUE TITLE
Cannot locate file for Mixpanel

### ISSUE THREAD

**Issue by jaga-me** [davodesign84/react-native-mixpanel#105]
Hi,

Followed the instructions for installing in iOS but im getting these errors

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lMixpanel
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lMixpanel is not an object file (not allowed in a library)

**Comment by chmac** [comment]
Did you find a solution? I have the same issue here.

**Comment by AlmogRnD** [comment]
+1 I'm getting the same issue 

```
ld: library not found for -lMixpanel
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Did anyone get this working? Is the lib still being supported?

**Comment by chmac** [comment]
We did get this package running. Can't say if it's being maintained or not though!

The solution to this issue might have been to open the `.xcworkspace` file instead of the `.xcodeproj`. I started opening it like `open ios/fatMapRN.xcworkspace` instead of via xcode. Doing that, we got the whole thing running, but after installing this package opening the `.xcodeproj` would not work.

**Comment by AlmogRnD** [comment]
Got it working thanks
