### ISSUE TITLE
XCode 9: Cyclic dependency in module 'Darwin'

### ISSUE THREAD

**Issue by flavordaaave** [davodesign84/react-native-mixpanel#110]
I just upgraded to the GM of XCode 9 and get a build error related to Mixpanel:
```
Cyclic dependency in module 'Darwin': Darwin -> std -> Darwin
```

**Comment by sunweiyang** [comment]
I am also experiencing this issue.

**Comment by sunweiyang** [comment]
Dug into the issue -- Looks like the issue is using the Header Search Path `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include`. Once it's removed, building works on Xcode 9. Hope that this is useful for everyone.

![image](https://user-images.githubusercontent.com/12490625/30629129-051ef242-9d8f-11e7-8091-c097d4a63c1b.png)

**Comment by sunweiyang** [comment]
Pull request for addressing this issue: #111

**Comment by sunweiyang** [comment]
If you're doing this change yourself, make sure that the RNMixpanel.xcodeproj in your app's Libraries also has the offending Header Search Path removed. (To be safe, of course, perform the iOS installation steps again.)
