### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by guilhermecomum** [davodesign84/react-native-mixpanel#89]
Hi everyone,

I'm trying to get push notifications on android device, but it seems mixpanel do not sending the notifications.
Someone can give me an example how to configure?

I believe something related with this article is part of my issue.
https://mixpanel.com/help/questions/articles/why-arent-my-push-notifications-sending

Thanks!

**Comment by tomhschmidt** [comment]
Adding onto this. My notification handler code is firing in-app, but I don't actually get a push notif in the OS / in the Notification menu. Weird.

**Comment by alekseykarpenko** [comment]
@tomhschmidt i have the same behavior!

**Comment by alekseykarpenko** [comment]
@tomhschmidt  i've found a solution. U can use ```<receiver>``` as described in [Official Mixpanel Doc](https://mixpanel.com/help/reference/android-push-notifications), then your notifications will be shown both in-app and in OS:
```xml
        <receiver android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
                  android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="com.kromtech.atmm" />
            </intent-filter>
        </receiver>
```

**Comment by aceisScope** [comment]
@tomhschmidt Could you kindly tell a bit more about your notification handler? After integrating Mixpanel, I can receive push notification in the notification center, but really can't get my head around how to make a notification handler/receiver in react native so as to display the notification in app as an alert :(

**Comment by tomhschmidt** [comment]
@aceisScope I use FCM to handle remote notifs. There's an event handler that will fire when a new notif is received, and you can then choose what in-app logic / display you want to run

https://github.com/evollu/react-native-fcm

**Comment by aceisScope** [comment]
@tomhschmidt Thanks a lot! So if I've understood it correctly, you integrated both react-native-fcm and mixpanel, and you still configured the `AndroidManifest.xml` as the [official Mixpanel Android push tutorial](https://mixpanel.com/help/reference/android-push-notifications) to receive **push notifications from Mixpanel**, but use FCM to handle the received notifications? 
Sorry for asking such detailed questions. I've been stuck with using react-native-push-notification in my project, since both it and Mixpanel set up GCM services, and only one of the services works...

**Comment by mdusza** [comment]
@aceisScope did you managed to solve your problem?
I think that I have all configuration in place in my project, but still I'm not receiving notifications on my phone. Also, on mixpanel I can see users in 'people' section, and I'm able to send notification to the certain user but after that when I check 'messages' section on mixpanel, 'sent' column says 0 :/

**Comment by aceisScope** [comment]
@mdusza My problem was caused by [react-native-push-notification](https://github.com/zo0r/react-native-push-notification) which registers for the same GCM service as Mixpanel. It means former is "competing" over the latter for receiving push notifications. So as Tom suggested I use [react-native-fcm](https://github.com/evollu/react-native-fcm) instead to receive push, completely removing react-native-push-notification.

**Comment by kalek** [comment]
@alekseykarpenko Did you have notify message from mixpanel on Android ??

**Comment by alejandroledesma** [comment]
Hi everyone,

I'm trying to get push notifications on IOS, added the APNS token (copy and paste all code) and configured the certificates, but I have not managed to receive notifications. Also I use the FCM handle to notification push in Android.

Someone can give me an example or code how to configure?
Thanks and regards

**Comment by vuk-nikolic** [comment]
hey @alejandroledesma i'm in the same spot right now.
did you have any luck in the end?

**Comment by vuk-nikolic** [comment]
I just needed to add 
```objc
UIUserNotificationSettings *settings = [UIUserNotificationSettings settingsForTypes:UIUserNotificationTypeSound |
                                          UIUserNotificationTypeAlert | UIUserNotificationTypeBadge categories:nil];

[[UIApplication sharedApplication] registerUserNotificationSettings:settings];
[[UIApplication sharedApplication] registerForRemoteNotifications];
```

in 
```- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions```

**Comment by alejandroledesma** [comment]
Yes @vuk-nikolic,

Finally, my problem was the certificates iOS. In develop you have use the Sanbox APN certificate, and in production a Distribution APN.

Regards!!
